### ISSUE TITLE
Problem with converting widerface to darknet format

### ISSUE THREAD

**Issue by HikkaV** [the-house-of-black-and-white/morghulis#16]
Greetings, first of all i wanna say , that you've done a really nice job, as this framework is incredibly useful. But it seems that there is a problem with converting widerface to darknet format.After executing the export.py file i got only 3501 images and annotations from them, but train dataset of widerface consists of more than 12k images. How can i solve this problem?

**Comment by fabito** [comment]
That's weird @HikkaV, I'll have a look.

**Comment by HikkaV** [comment]
Thank you
